# mysql 配置
mysql:
  name: 'dispatch'
  host: 'localhost'
  port: 3306
  user: 'dgove'
  password: '123'

# 用户密码加密盐
key: 'dgove'

# 阿奇索授权完跳转url
web: 'http://117.72.38.81/dispatch/system.html#3'

# 定时任务
crontab:
  # 分 时 天 月 年
  - due: '0 6 * * *'
    task: 'dispatch.task.tbstatus_check_task'
  - due: '0 18 * * *'
    task: 'dispatch.task.tbstatus_check_task'


